### ISSUE TITLE
Consider renaming the loading and serialisation package to 'fileIO'

### ISSUE THREAD

**Issue by amithjkamath** [ubern-mia/pyradise#3]
@ruefene  - the more I think of this, the more it feels like typical users would not really connect with the name: serialization to save data to files. I understand it is technically correct, and along the same lines, you could also name the loading package 'deserialization'. 

However, to make this easier to read and understand, I propose combining the two and renaming the entire package 'fileIO' or something similar. 

I imagine 

    from pyradise import fileio

    fileio.load(...)
    fileio.save(...)

to look cleaner than 

    from pyradise import serialization 
    from pyradise import loading

    ....

**Comment by mauricioreyes** [comment]
Makes a lot of sense! Cheers
Mauricio

--
Mauricio Reyes, Prof. Dr.
ARTORG Center for Biomedical Engineering Research
Center for AI in Medicine
University of Bern
http://www.caim.unibe.ch
http://www.artorg.unibe.ch
http://www.mauricioreyes.me/
twitter.com/mreyesag<https://twitter.com/mreyesag>
ch.linkedin.com/in/mauricioreyes<http://ch.linkedin.com/in/mauricioreyes/>/

From: AKA Math ***@***.***>
Reply to: ubern-mia/pyradise ***@***.***>
Date: Tuesday, 23 August 2022 at 22:43
To: ubern-mia/pyradise ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ubern-mia/pyradise] Consider renaming the loading and serialisation package to 'fileIO' (Issue #3)


@ruefene<https://github.com/ruefene> - the more I think of this, the more it feels like typical users would not really connect with the name: serialization to save data to files. I understand it is technically correct, and along the same lines, you could also name the loading package 'deserialization'.

However, to make this easier to read and understand, I propose combining the two and renaming the entire package 'fileIO' or something similar.

I imagine

from pyradise import fileio



fileio.load(...)

fileio.save(...)

to look cleaner than

from pyradise import serialization

from pyradise import loading



....

**Comment by ruefene** [comment]
@amithjkamath - according to our discussion i changed the project structure to consist just of three main packages (data, fileio, process) which should simplify things for the user (see 786d960d9d1fe8cd0c3b5c74c4744f5e8084477f). I consider the issue as closed.

**Comment by amithjkamath** [comment]
Perfect! Thanks for the proactiveness and discussions around this!
