### ISSUE TITLE
Consider renaming the conversion and curation modules to convert and curate

### ISSUE THREAD

**Issue by amithjkamath** [ubern-mia/pyradise#4]
This is a general comment: I would imagine avoiding 'ion' and 'ing' suffixes to package names will make the code read better. This way, the names indicate only what they do, and not the process of doing it (I hope this makes sense).

If you (@ruefene) think I can make this change myself, please let me know here and I can create a new pull request with these changes. 

Thanks!

**Comment by ruefene** [comment]
A very good idea :) I hope the new structure is clearer :)
